import { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Header } from '@/components/header/header'
import { Footer } from '@/components/footer/footer'
import { Main } from '@/components/main/main'
import '@/styles/globals.scss'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Next App',
  description: 'Generated by create next app',
  authors: { name: "Nick1091", url: "https://github.com/Nick1091" }
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='wrapper'>
          <Header/>
          <Main>
            {children}
          </Main>
          <Footer/>
        </div>
      </body>
    </html>
  )
}
